gonum/lapack

README.md

README: only report failure on master

---

cgo/clapack/clapack.go
cgo/clapack/genLapack.pl

This is primarily for gonum dev use, but will aid others.
PTAL @btracey

cgo/clapack: add autogenerated links to the fortran code

---

testlapack/dgetf2.go

Also remove Errorf in favour of Error where possible.
See https://github.com/xianyi/OpenBLAS/issues/610#issuecomment-127095782

testlapack: be more tolerant of singularity misses

---

cgo/lapack_test.go

lapack/cgo: re-enable Dlantr test

---

cgo/lapack_test.go

lapack/cgo: re-enable Dpocon test

---

lapack64/lapack64.go

lapack64: don't use overloaded English word

---

native/dgecon.go

Fixes gonum/matrix/issues/273.

native: fix cond result for zero matrix

---

native/dgetrf.go
native/dlacpy.go
native/dlaswp.go
native/dlatrs.go
native/dorml2.go
native/dormlq.go
native/dormqr.go
native/dtrtri.go

native: clean up return use

---

native/ilaenv.go

native: fix spelling error

---

.travis/linux/ATLAS/install.sh
.travis/linux/OpenBLAS/install.sh
.travis/linux/gonum/install.sh

Added set -ex and some comments to install scripts
Same as https://github.com/gonum/blas/pull/156

add set -ex and comments to install scripts

---

native/dsytrd.go

native: fix missed matrix for typography changes

---

lapack64/lapack64.go

Revert "Adddsyev"

---

native/dlasq2.go
native/dlasq3.go
native/dsteqr.go
native/dsterf.go

native: reduce use of goto

---

lapack64/lapack64.go

lapack64: improve doc for Potrf

---

native/dlanv2.go
native/lapack_test.go
testlapack/dlanv2.go

A tiny piece into the eigen puzzle but one has to start somewhere. PTAL

native: add Dlanv2

---

cgo/lapack.go
native/dormqr.go

cgo,native: fix Dormqr work checks

---

cgo/lapack.go
native/dlaqr1.go
native/general.go
native/lapack_test.go
testlapack/dlaqr1.go

native: add Dlaqr1

---

native/dlasy2.go

Bug report to upstream was accepted:
http://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=13&t=4975

native: set ok to false in 2x2 case in Dlasy2

---

native/dlahqr.go
native/lapack_test.go
testlapack/dlahqr.go

Another PR on the slightly heavier side. PTAL @kortschak @btracey

native: add Dlahqr

---

cgo/lapack.go
cgo/lapack_test.go
native/dtrexc.go
native/lapack_test.go
testlapack/dtrexc.go
testlapack/general.go

Needs #162 but submitting in advance to give time for review. The test for this covers Dlaexc completely, so it serves as a further confirmation of correctness of Dlaexc.

native,cgo: add Dtrexc

---

native/dlahqr.go

Let me know if I should undo here also the splitting of the `If unconverged is ... and wantt is ...` paragraphs.

native: polish docs for Dlahqr

---

cgo/clapack/clapack.go
cgo/clapack/genLapack.pl
cgo/lapack.go
lapack.go

Partly addresses #160 and #163

lapack,cgo: rename CompSV to Comp

---

cgo/lapack.go
lapack64/lapack64.go
native/dgels.go
native/dormbr.go
native/dormqr.go
testlapack/dormqr.go

native: fix computation of ldwork in Dormqr

---

native/dlahqr.go
native/dlaqr2.go
native/dlaqr4.go
native/dlaqr5.go
native/iparmq.go
native/lapack_test.go
testlapack/dlahqr.go
testlapack/dlaqr4.go
testlapack/dlaqr5.go

Still contains some TODOs but ready for review. Includes some cleanup in other routines and a fix for a "tiny" confusion in Dlaqr5 that were too troublesome to send as separate PRs.
Needs #177.

native,testlapack: add Dlaqr4

---

cgo/lapack.go
cgo/lapack_test.go
lapack.go
native/dgebal.go
native/general.go
native/lapack_test.go
testlapack/dgebal.go
testlapack/general.go

native,cgo: add Dgebal

---

native/dlaqr04.go
native/dlaqr23.go
native/lapack_test.go
testlapack/dlaqr04.go

native,testlapack: change Dlaqr4 into Dlaqr04

---

cgo/lapack.go
cgo/lapack_test.go
native/dgebak.go
native/lapack_test.go
testlapack/dgebak.go
testlapack/dgebal.go
testlapack/general.go

native,cgo: add Dgebak

---

cgo/lapacke/genLapacke.pl
cgo/lapacke/lapacke.go

@vladimir-ch Please take a look.
Fixes #183.

cgo/lapacke: make *hseqr return int

---

cgo/lapacke/genLapacke.pl
cgo/lapacke/lapacke.go

@vladimir-ch Please take a look.
Fixes #187.

cgo/lapacke: make *geev,*geevx return int

---

cgo/lapack.go
lapack.go
native/dtrevc3.go
native/general.go
native/ilaenv.go
native/lapack_test.go
testlapack/dtrevc3.go
testlapack/general.go

For some reason this PR has been extremely onerous. Sometimes one ends up wishing the left eigenvectors didn't exist. On the other hand, cries of hosanna for slice bounds checking and our strict panics.
The tests seem solid and give me some confidence, but I still feel some tripidation. Please review carefully.

native: add Dtrevc3

---

cgo/lapack.go
cgo/lapack_test.go
lapack.go
lapack64/lapack64.go
native/dgebak.go
native/dgeev.go
native/lapack_test.go
testlapack/dgebak.go
testlapack/dgeev.go
testlapack/general.go
testlapack/test_matrices.go

I still want to extend the testing a bit but you can start looking at this, especially the testing.

native,cgo: add Dgeev

---

cgo/lapack.go
lapack.go
lapack64/lapack64.go
native/dgebak.go
native/dgeev.go
native/dlaqr23.go
native/dsyev.go
native/dtrevc3.go
native/dtrexc.go
native/general.go
testlapack/dgebak.go
testlapack/dgeev.go
testlapack/dsyev.go
testlapack/dtrevc3.go
testlapack/dtrexc.go

First part of clean up for byte types and consts related to eigenvalue solvers. Review on per-commit basis.
Updates #163

all: clean up eigenproblems-related types and consts 

---

cgo/lapack.go
lapack.go
native/dgeev.go
native/dhseqr.go
native/dlaqr23.go
native/dsteqr.go
native/dsyev.go
native/dtrexc.go
native/general.go
testlapack/dhseqr.go
testlapack/dsteqr.go
testlapack/dtrexc.go

lapack: clean up eigendecomposition types and constants

---

testlapack/dgecon.go
testlapack/dgetf2.go
testlapack/dgetrf.go
testlapack/dgetri.go
testlapack/dgetrs.go
testlapack/dlacpy.go
testlapack/dlaev2.go
testlapack/dlansy.go
testlapack/dlantr.go
testlapack/dpocon.go
testlapack/drscl.go
testlapack/dtrcon.go
testlapack/dtrti2.go
testlapack/dtrtri.go

testlapack: add missing copyright headers

---

cgo/lapack.go
cgo/lapack_test.go
native/lapack_test.go
testlapack/dlacn2.go

cgo,testlapack: add Dlacn2 and its test

---

cgo/lapack.go
native/dlacn2.go

Sorry about the forgotten formatting.

native,cgo: update docs for Dlacn2

---

cgo/lapacke/generate_lapacke.go
cgo/lapacke/lapacke.go

cgo/lapacke: allow any uplo character in xlaset and xlacpy

---

cgo/lapack.go
cgo/lapack_test.go
native/dlascl.go
native/dlaset.go
native/dlasrt.go
native/general.go
native/lapack_test.go
testlapack/dlapy2.go
testlapack/dlascl.go
testlapack/dlaset.go
testlapack/dlasrt.go

Do we want tests for these routines? I plan to add one for Dlaswp, what about the rest?
Updates #142

cgo: add Dlapy2, Dlascl, Dlaset, Dlasrt, Dlaswp

---

cgo/lapack.go
native/dgeqrf.go

@vladimir-ch Please take a look.
Fixes #225.

cgo,native: fix optimal work length return

---

cgo/lapack.go
cgo/lapack_test.go
native/dlapll.go
native/dlapmt.go
native/general.go
native/lapack_test.go
testlapack/dlapll.go
testlapack/dlapmt.go

cgo,native: implement dlapmt and dlapll, and tests

---

cgo/lapack.go
cgo/lapack_test.go

Updates #142 
@kortschak @btracey PTAL

cgo: add Dsterf

---

native/dsytrd.go

Closes #233 
@kortschak @btracey PTAL

native: add length checks to Dsytrd

---

cgo/lapack.go
cgo/lapack_test.go
native/dsytrd.go
testlapack/dsytrd.go

Updates #142 
@kortschak @btracey PTAL

cgo: add Dsytrd

---

cgo/lapack.go
cgo/lapack_test.go
native/dorgtr.go
testlapack/dorgtr.go

cgo: add Dorgtr

---

cgo/lapack.go
cgo/lapack_test.go
native/dsteqr.go

@kortschak @btracey PTAL
Closes #142

cgo: add Dsteqr

---

cgo/lapack.go
native/dlange.go

@btracey @vladimir-ch  Please take a look.

cgo,native: fix doc typo for Dlange

---

native/dlaqr04.go
native/dlaqr5.go
testlapack/dgehrd.go

This has been on my todo list since I finished Dgeev. It is not essential but at least I can check it as done. PTAL

native,testlapack: some small cleanup in the eigensolver

---

testlapack/general.go

testlapack: ensure non-equality of NaN

---

cgo/lapack.go
cgo/lapack_test.go
native/dgeqp3.go
native/dlaqp2.go
native/dlaqps.go
native/general.go
native/lapack_test.go
testlapack/dgeqp3.go
testlapack/dlaqp2.go
testlapack/dlaqps.go
testlapack/general.go

Documentation probably needs work and tests also.
Updates #218.

cgo,native: implement dgeqp3 and dependencies

---

cgo/lapack.go
cgo/lapack_test.go
native/dormbr.go
testlapack/dormbr.go

LAPACKE bugs have been now fixed both in Reference LAPACK and in OpenBLAS.
I will wait for Travis to finish before merging.
Fixes #241

cgo: enable tests for Dormbr and Dormlq

---

cgo/lapack.go
cgo/lapack_test.go
lapack.go
native/dlags2.go
native/dtgsja.go
native/general.go
native/lapack_test.go
testlapack/dlags2.go
testlapack/dtgsja.go
testlapack/general.go

@vladimir-ch @btracey Please take a look.
Needs tests for dtgsja — there is a cgo reference implementation to compare against.
Updates #218.

cgo,native: implement dtgsja part of dggsvd3 tree

---

cgo/lapack.go
native/dlarfb.go
native/dormlq.go
testlapack/dormbr.go
testlapack/dormlq.go

The first commit contains the fix plus tests that would have triggered the bug (panic in Dlarfb). The additional test case in Dormbr is how I found the panic originally. While looking for the cause, I made some clean up to help me isolate the issue, which I also include here.

native: fix wrong ldwork in Dormlq

---

testlapack/dpotrf.go
testlapack/matgen.go

Also, "test" the new function Dlagsy by using it to generate a not positive definite matrix for an expected-failure test case for Dpotrf. PTAL

testlapack: add Dlagsy

---

testlapack/dpotrf.go
testlapack/matgen.go

testlapack: add unused parameter k to Dlagsy for future implementation

---

native/general.go

@vladimir-ch Please take a look.

native: make constants constant where possible

---

cgo/lapack.go
native/dgebrd.go
native/dgelqf.go
native/dorgqr.go

cgo: remove compatibility comments about work slice

---

cgo/lapack.go
native/dgebrd.go
native/dgesvd.go

@vladimir-ch @btracey  Please take a look.
Updates #228.

native: reduce allocations in Dgesvd

---

cgo/lapack.go
cgo/lapack_test.go
lapack.go
lapack64/lapack64.go
native/dgeqp3.go
native/dgerq2.go
native/dgerqf.go
native/dggsvd3.go
native/dggsvp3.go
native/dlapmt.go
native/dormr2.go
native/lapack_test.go
testlapack/dgerq2.go
testlapack/dgerqf.go
testlapack/dggsvd3.go
testlapack/dggsvp3.go
testlapack/dormr2.go
testlapack/general.go

@btracey @vladimir-ch If you can find some time to take a look and point out the errors I've made, that would be greatly appreciated. There is no urgency here.
Closes #218.

cgo,native: implement dggsvd3

---

native/dggsvp3.go
testlapack/dggsvd3.go
testlapack/dggsvp3.go

native,testlapack: fix bounding of cleanup

---

native/dlatrs.go
native/lapack_test.go
testlapack/dlatrs.go
testlapack/general.go
testlapack/matgen.go

Bigger PR than planned but one thing leads to another ...
If you wish I can remove the last commit and submit it separately. I reduced the indentation to make it easier for me to compare with the reference.
It would be nice to export dlattr later but I don't think it's ready.
@kortschak  @btracey  PTAL

native,testlapack: fix Dlatrs and increase its coverage

---

native/dormlq.go
testlapack/dormlq.go

native: avoid allocation in Dormlq
