gonum/lapack

.travis.yml, .travis/linux/ATLAS/install.sh, .travis/linux/OpenBLAS/install.sh, .travis/linux/gonum/install.sh, .travis/test-coverage.sh
As explained in
https://groups.google.com/d/msg/gonum-dev/GKJjAtDxR9I/n0FD7WvvN5AJ
Removed notifications and go tip, simplified code, added some comments,
put all travis related code (except for .travis.yml) into .travis/
A note for discussion: I named the build that relies on gonum/blas "gonum," where previously we have called it native, because native is typically used to describe something that is processor dependent and not portable, while the gonum/blas library is the opposite.  I also fiddled around a little with getting the ATLAS build to work, but I was having issues linking the lapack functions so its install script is not complete.  It is not enabled for builds, although it would be nice because it takes much less time to install.
PTAL
=> cleanup .travis.yml and associated files

native/dpotf2.go
Saw in review, to far from a changed line to get a comment [+] button.
@btracey please take a look
=> native: fix Dpotf2 doc comment

.travis.yml, .travis/linux/OpenBLAS/install.sh
Also output OpenBLAS sha during build.
Merging because it fixes the build.
TBR @jonlawlor
=> travis: update go1.3beta2 -> go1.5beta3

lapack.go, lapack64/lapack64.go, native/dpocon.go
The condition number routines are used to check the condition number of a matrix before attempting a linear solve.
=> Add the Dxxcon routines to lapack64.

cgo/clapack/clapack.go, cgo/clapack/genLapack.pl
=> cgo/clapack: add hook for specifying blas.All uplo value

cgo/clapack/clapack.go, cgo/clapack/genLapack.pl, cgo/clapack/lapacke.h, cgo/clapack/lapacke_utils.h
=> cgo/clapack: update codegen for LAPACKE 3.6

native/general.go
=> native: make small constants more reader friendly

cgo/lapack.go, native/dgebrd.go, native/dlabrd.go, native/dlarfb.go, native/dlartg.go, native/dlatrd.go, native/dsytd2.go
Use square brackets throughout and use an (almost) uniform matrix cell layout. All matrix cells are right justified and cells are the width of the largest element (negative signs treated according to taste here). Large matrices have 2 space gutter between elements and 2x2 matrices or smaller have 1 space gutter.
Fixes #97.
=> {cgo,native}: fix matrix typography

cgo/lapack.go, lapack.go, lapack64/lapack64.go, native/dgebd2.go, native/dgebrd.go, native/dgelq2.go, native/dgeql2.go, native/dgeqr2.go, native/dlabrd.go, native/dlarft.go, native/dlatrd.go, native/dorg2l.go, native/dorg2r.go, native/dorgl2.go, native/dorglq.go, native/dorgql.go, native/dorgqr.go, native/dorgtr.go, native/dsytd2.go, native/dsytrd.go
* Use zero-based indexing for elementary reflectors (almost) everywhere.
* Denote elementary reflectors as H(i), not H_i, not H[i].
* Remove some lint.
=> Fix, clean up, and unify documentation of elementary reflectors

testlapack/general.go
Simply remove the checking of NaNs after the matrix because everywhere where I use this function the slices are allocated tightly anyway.
Sorry that this slipped me through.
=> testlapack: avoid panic in *OutsideAllNan for zero-sized matrices

.travis/linux/ATLAS/install.sh, .travis/linux/OpenBLAS/install.sh, .travis/linux/gonum/install.sh
Same as gonum/blas#184 - use a prebuilt cache of the OpenBLAS libraries instead of recompiling every time.
=> populate OpenBLAS cache, unset -ex in scripts

native/dlaexc.go, testlapack/dlaexc.go, testlapack/general.go
I'm sorry. If only someone could elucidate what exactly I was thinking when I wrote the original ...
Such a wholly unremarkable off-by-one error. Why this went (almost) undetected: because of the error, the matrix d did not have zeros where it should, therefore Dlaexc returned with a false in the `> thresh` checks, and therefore the tests exited early `if !ok`. I did notice that Dlaexc returned sometimes with a false but I didn't notice that it was always except for the trivial or 1x1 cases. Therefore I mistakenly attributed it to floating point effects.
The tests are a different story. I noticed **something** is wrong with them after fixing the indexing error. I don't know what I was thinking there.
PTAL @kortschak @btracey
=> native,testlapack: fix Dlaexc and its test

native/dlaexc.go, testlapack/dlaexc.go
`Dtrexc` uses (depends on) this behavior, so it makes sense to make it more formal by documenting and testing it. PTAL
=> native,testlapack: document and test that Dlaexc return true when n1=n2=1

native/dlahqr.go, testlapack/dlahqr.go
Previously, the zero value of the returned integer `info` was used to indicate
success. This is wrong because it is a 0-based index unlike the reference LAPACK
where it is a 1-based index and therefore 0 is available for such purpose. This
commit adds `ok bool` to the returned values from Dlahqr.
=> native: add ok to returns from Dlahqr

native/dlahqr.go, testlapack/dlahqr.go
If the returned integer is a 1-based size and not a 0-based index, we can use 0 to indicate success (i.e., all eigenvalues have converged) and thus the `converged bool` is not necessary.
Also polished the docs a little.
PTAL
=> native: change Dlahqr back to return single integer

cgo/lapack.go, native/dgehrd.go, native/dlaqr2.go, native/dormhr.go, native/lapack_test.go, testlapack/dgehrd.go, testlapack/dlaqr2.go, testlapack/dormhr.go
The documentation of reference DLAQR2 is quite loose or even incorrect in some places, so most of the differences in this PR come from that. Further, some of the documented restrictions on input values are in fact allowed and handled in the reference, I'm stricter and usually panic. That's another source of tiny differences.
Also, it seems that having a set of matrices with known eigenvalues will be soon very useful / necessary for testing. Any suggestions on where to get them, and how and where to store them? Using random matrices and computing their eigenvalues in e.g. Octave is of course possible but I'm after "difficult" eigenvalue problems that would trigger some exceptional paths in the code not taken by random matrices. Matrix Market is an option, their matrices for eigenvalue …
=> native: add Dlaqr2

testlapack/dgeev.go
- Fix wrong calculation of `lwork` for intermediate workspace size
- ~~Use positive stride even if the corresponding matrix is not referenced or has zero size. While we don't care, cgo implementations sometimes do.~~
=> testlapack: fix lwork in test for Dgeev

cgo/lapack.go, cgo/lapack_test.go
Updates #142.
Depends #141.
Dlarfg and Dlarft pass. Dlarfb is not a happy camper:
```
$ CGO_LDFLAGS="-L/usr/local -lopenblas" go test -run Dlarfb
** On entry to DTRMM  parameter number 11 had an illegal value
** On entry to DTRMM  parameter number 11 had an illegal value
** On entry to DTRMM  parameter number 11 had an illegal value
** On entry to DTRMM  parameter number 11 had an illegal value
** On entry to DTRMM  parameter number 11 had an illegal value
** On entry to DTRMM  parameter number 11 had an illegal value
** On entry to DTRMM  parameter number 11 had an illegal value
** On entry to DGEMM  parameter number 13 had an illegal value
** On entry to DTRMM  parameter number 11 had an illegal value
** On entry to DGEMM  parameter number 10 had an illegal value
** On entry to DTRMM …
```
=> cgo: add Dlarf[bgt]

cgo/lapack.go, cgo/lapack_test.go, native/dorgql.go, native/general.go, testlapack/dorgql.go
I had to rewrite the test because LAPACKE does not provide the routines that it had been using. It still relies on Dlarfg which could be avoided if desired but I think it's ok like this.
Updates #142
=> cgo: add Dorgql, rewrite its test and update its docs

native/dsteqr.go
In the call to Dlascl we pretend that the diagonals d and e are 1-column
wide matrices. Reference LAPACK is column-major, so the value of the
stride should not matter, which is demonstrated by the (probably
arbitrary) value of n. We are row-major, so the stride should be set to
the number of columns, that is, 1.
=> native: fix wrong stride in Dsteqr

testlapack/matgen.go
This is a first step in my effort on #232 . In Reference LAPACK, `testing/MATGEN` has routines that probably contain what we need. I'm trying to follow their interface although not as strictly as in native, we can deviate here and be more Go-like. Let me know if you think the random number part could be handled better. I also thought it might be a good idea to export these matrix generation functions.
=> testlapack: add Dlatm1

native/dlartg.go, testlapack/dlartg.go
Also, modify Dlartg test to use tiny and huge input values to cover all code paths.
=> native: fix safe minimum and maximum values in Dlartg

.travis/linux/OpenBLAS/install.sh, .travis/linux/gonum/install.sh, .travis/test-coverage.sh
Adding two tests in testlapack package recently triggered the whole testlapack package to be included in coverage testing. As a result, our official coverage dropped from about 80% to about 30%. This PR removes testlapack package from coverage testing. @jonlawlor @kortschak PTAL
I also remove two unnecessary calls to go get mat64. Also, native package is tested twice, once with BLAS_LIB=gonum and once with BLAS_LIB=OpenBLAS (and then both again when doing coverage). However, I don't think that this changes the BLAS library used because in native we use blas64, its default implementation is blas/native and this is not changed by linking against OpenBLAS. Am I missing something or could we speed up the travis tests by not testing native twice?
=> travis: remove testlapack from coverage testing
